### ISSUE TITLE
Do you still use percona's exporter in this image?

### ISSUE THREAD

**Issue by MohamedMSaeed** [bitnami/bitnami-docker-mongodb-exporter#8]
**Description**

I upgraded the image from tag `0.10.0-debian-10-r69` to `0.20.1-debian-10-r38` and all metrics are lost! I can see that all metrics are renamed and some of them are deleted. 

I installed the percona's last version to make sure that they didn't change their metrics. They didn't. 

And if you already changed the exporter code, which dashboards should we use? 

Thanks in advance

**Comment by juan131** [comment]
Hi @MohamedMSaeed 

Yes, we are still using the Percona's exporter: https://github.com/percona/mongodb_exporter

As you can see at https://github.com/percona/mongodb_exporter/releases/tag/v0.20.1:

> This is a new branch of Exporter. It's a completely new code and will be the default soon. As for now, this used in PMM 2.10.0+.

Our system automatically detected this `0.20.1` version since it tracks the tags available https://github.com/percona/mongodb_exporter/releases and released it. However, it looks like it's a completely new code, and we should treat it like a major version.

Please revert to version `0.10.0` in the meantime. Thanks for reporting it.

**Comment by jonhatallasf** [comment]
@MohamedMSaeed I believe the magic fix will be the compatibilty mode flag

https://github.com/percona/mongodb_exporter/tree/exporter_v2#flags

just pass `--compatible-mode` to mongodb exporter and you should get your old metrics

**Comment by juan131** [comment]
That's a great suggestion @jonhatallasf !! Thanks so much for sharing it!! 

@MohamedMSaeed if you're using the Bitnami MongoDB chart, theres'a a `metrics.extraFlags` parameter that you can use to add extra flags to the MongoDB exporter.

**Comment by juan131** [comment]
By the way, if you check our latest releases, you'll find that we reverted back and we're releasing the `0.11` series.

**Comment by JuniorCtba** [comment]
@juan131 do you know if there are other grafana dashboards that can be used with this new version?

**Comment by carrodher** [comment]
As Juan rightly said and talking about the exporter itself, we are releasing both versions, see https://github.com/bitnami/bitnami-docker-mongodb-exporter#supported-tags-and-respective-dockerfile-links then about choose a Grafana dashboard to show the data exported by the old or the new version is something we are not used to working with. I recommend you to ask this question in the upstream project forums/repositories

**Comment by JuniorCtba** [comment]
@carrodher there is a place where I can find the equivalent name for each metric?
Example
mongodb_op_counters_total old -  mongodb_xxx_xxx new

**Comment by carrodher** [comment]
I found something in the release notes, but I am not sure if it's what you are looking for, see https://www.percona.com/blog/2020/09/22/new-mongodb-exporter-released-with-percona-monitoring-and-management-2-10-0/ from https://github.com/percona/mongodb_exporter/releases/tag/v0.20.1

It is something related to the upstream project (the exporter itself) instead of the Bitnami container, probably you can find more useful information in the upstream repo via docs, existing PRs/Issues, README, etc

**Comment by ahmettortumlu** [comment]
> @MohamedMSaeed I believe the magic fix will be the compatibilty mode flag
> 
> https://github.com/percona/mongodb_exporter/tree/exporter_v2#flags
> 
> just pass `--compatible-mode` to mongodb exporter and you should get your old metrics

how can I add compatible mode property at docker-compose file, is there any environment variable to enable that?

**Comment by carrodher** [comment]
There is not any available environment variable for this purpose, in that case, you need to customize the container image by modifying the `ENTRYPOINT` in the _Dockerfile_ and building your own image. You can add the flag directly in the entry point
https://github.com/bitnami/bitnami-docker-mongodb-exporter/blob/762ce56d12b4c975fa8ad27e0c3a51d26c8df4c5/0/debian-10/Dockerfile#L27
